### ISSUE TITLE
一起来上线肝服吧！功能建议

### ISSUE THREAD

**Issue by Natsusomekeishi** [XiaMoHuaHuo-CN/CatSero#114]
### 功能描述

1. 晚上有玩家熬夜上线肝服，增加变量选项，提示上线的时候，提示“xxx竟然大半夜上线肝服！”
2. 玩家可通过于群内发送指令/cbind @QQ名（后台匹配QQ号）绑定上线通知，实现一个玩家上线之后，机器人艾特与其绑定的玩家提示“@XXX XX已经上线肝服了！你还不快来！”实现好朋友的一起快乐玩耍！

以上均是在长久支持使用最新版本后，与众多玩家想实现的新功能~qwq

### 使用方法

1.

**Comment by XiaMoHuaHuo-CN** [comment]
草 不错

**Comment by Muska-Ami** [comment]
CatSero v3 计划开始，不再处理v2 Issues，Close.
