### ISSUE TITLE
当玩家进入服务器时报错

### ISSUE THREAD

**Issue by vongwei666** [XiaMoHuaHuo-CN/CatSero#122]
### 问题描述

当玩家进入服务器时就会报错

**Comment by vongwei666** [comment]
/

**Comment by vongwei666** [comment]
[02:19:53 WARN]: [CatSero] [Catch] 捕获到一个错误
[02:19:53 WARN]: [CatSero] [Catch] 错误类型: org.sqlite.SQLiteException
[02:19:53 WARN]: [CatSero] [Catch] 捕获消息: [SQLITE_ERROR] SQL error or missing database (no such table: RECORDS)
[02:19:53 WARN]: [CatSero] [Catch] 详细信息:      - org.sqlite.core.DB.newSQLException(DB.java:1030)
     - org.sqlite.core.DB.newSQLException(DB.java:1042)
     - org.sqlite.core.DB.throwex(DB.java:1007)
     - org.sqlite.core.NativeDB.prepare_utf8(Native Method)
     - org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
     - org.sqlite.core.DB.prepare(DB.java:257)
     - org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
     - [QQ机器人]CatSero-2.3.3.jar//com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110)
     - [QQ机器人]CatSero-2.3.3.jar//com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
     - [QQ机器人]CatSero-2.3.3.jar//moe.xmcn.catsero.utils.WhiteListDatabase.getCode(WhiteListDatabase.java:289)
     - [QQ机器人]CatSero-2.3.3.jar//moe.xmcn.catsero.listeners.qwhitelist.RefuseNoWhiteList.onPlayerPreLogin(RefuseNoWhiteList.kt:56)
     - com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source)
     - org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
     - co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
     - [插件管理]Yum.jar//pw.yumc.Yum.inject.ListenerInjector.execute(ListenerInjector.java:105)
     - org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
     - io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
     - io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
     - org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
     - net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:394)
     - net.minecraft.server.network.LoginListener$1.run(LoginListener.java:279)
     - java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
     - java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
     - java.base/java.lang.Thread.run(Thread.java:833)

[02:19:53 WARN]: [CatSero] [Catch] 如您认为这不是配置错误、网络原因导致的问题，请前往此处报告：
[02:19:53 WARN]: [CatSero] [Catch] https://github.com/XiaMoHuaHuo-CN/CatSero/issues

**Comment by XiaMoHuaHuo-CN** [comment]
大概知道是什么原因了

**Comment by XiaMoHuaHuo-CN** [comment]
#119
