### ISSUE TITLE
支持BC端

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [XiaMoHuaHuo-CN/CatSero#128]
### Discussed in https://github.com/XiaMoHuaHuo-CN/CatSero/discussions/127

<div type='discussions-op-text'>

<sup>Originally posted by **LinAnSalA** April  6, 2023</sup>
作者可以为插件支持BC跨服端吗 因为现有的BC跨服端机器人的作者貌似退圈了</div>

**Comment by XiaMoHuaHuo-CN** [comment]
目前的思路是通过Bukkit版本与BC版本建立双向通道传输数据

**Comment by Muska-Ami** [comment]
CatSero v3 计划开始，不再处理v2 Issues，Close.
