### ISSUE TITLE
建议增加自由执行指令，而不是只有ban/op等

### ISSUE THREAD

**Issue by xiaole29999** [XiaMoHuaHuo-CN/CatSero#18]
### 功能描述

允许使用者（管理）可以自由执行服务器的大部分命令，而不是目前的ban/op/tps等

### 使用方法

前置条件：此用户在qq-op项内存在
希望效果：可以通过指令前缀如#来执行命令（比如#tps），机器人将反馈执行这行命令后的信息

### 额外说明

能不能修下聊天转发啊(划去

**Comment by XiaMoHuaHuo-CN** [comment]
我正在想自定义命令头
虽然效果和你现在描述的不是特别一致，但是效果大概是
```
!<command> <options> ...
```
同时支持原来的`!catsero <options> ...`

**Comment by XiaMoHuaHuo-CN** [comment]
> 能不能修下聊天转发啊(划去
聊天转发先用Chat2QQ代替吧

**Comment by xiaole29999** [comment]
okok

**Comment by XiaMoHuaHuo-CN** [comment]
https://github.com/XiaMoHuaHuo-CN/CatSero/actions/runs/2897873151

**Comment by xiaole29999** [comment]
啊啊？这么快，谢谢大佬了
