### ISSUE TITLE
聊天转发不显示人的昵称

### ISSUE THREAD

**Issue by xiaole29999** [XiaMoHuaHuo-CN/CatSero#20]
### 问题描述

QQ转发到MC的消息，部分群员的昵称不会显示
初步判断该群员没有改群昵称，而插件只请求获取了群昵称，没有获取QQ的昵称

### 复现方法

只要群成员没有群昵称并且发送消息，此bug就会触发

### 服务端版本

paper-1.19

### CatSero 版本

1.2-pre1

### 服务端日志

```text
无相关日志
```

### 额外说明

![8BK480HDJI{LVU)K0FFW%SP](https://user-images.githubusercontent.com/111669037/186333596-ed4d3154-0906-4151-9fff-eba9786fd852.png)

**Comment by xiaole29999** [comment]
注：有群昵称的玩家不会触发此bug
![7%F%( L6T09U(O_J71PD}E](https://user-images.githubusercontent.com/111669037/186333835-629bb1bc-796e-4196-9548-dfa30c7a108f.png)

**Comment by XiaMoHuaHuo-CN** [comment]
目前暂时没空修这个Bug 如果是Chat2QQ那么你要打开如果玩家QQ没有群名字时获取玩家用户信息名称

**Comment by xiaole29999** [comment]
> 目前暂时没空修这个Bug 如果是Chat2QQ那么你要打开如果玩家QQ没有群名字时获取玩家用户信息名称
大佬这个是您的插件，不是chat2qq

**Comment by xiaole29999** [comment]
> 目前暂时没空修这个Bug 如果是Chat2QQ那么你要打开如果玩家QQ没有群名字时获取玩家用户信息名称

大佬这是您的插件，不是chat2qq

**Comment by XiaMoHuaHuo-CN** [comment]
> > 目前暂时没空修这个Bug 如果是Chat2QQ那么你要打开如果玩家QQ没有群名字时获取玩家用户信息名称
> 
> 大佬这是您的插件，不是chat2qq

好的 有空我再看看 快开学了更新不会那么频繁

**Comment by xiaole29999** [comment]
> > > 目前暂时没空修这个Bug 如果是Chat2QQ那么你要打开如果玩家QQ没有群名字时获取玩家用户信息名称
> > 
> > 
> > 大佬这是您的插件，不是chat2qq
> 
> 好的 有空我再看看 快开学了更新不会那么频繁

OKOK

**Comment by XiaMoHuaHuo-CN** [comment]
看我最新构建可不可以用 可以再关Issue

**Comment by XiaMoHuaHuo-CN** [comment]
看最新的Actions构建
能用再关Issue

**Comment by xiaole29999** [comment]
![image](https://user-images.githubusercontent.com/111669037/186348399-95615ff4-957c-4cb4-ab54-a4ad03e8a843.png)
貌似并不行

**Comment by XiaMoHuaHuo-CN** [comment]
> ![image](https://user-images.githubusercontent.com/111669037/186348399-95615ff4-957c-4cb4-ab54-a4ad03e8a843.png) 貌似并不行

emm 估计返回的不是null而是空字符串
我再改改

**Comment by XiaMoHuaHuo-CN** [comment]
https://github.com/XiaMoHuaHuo-CN/CatSero/actions/runs/2917117948

**Comment by xiaole29999** [comment]
已经解决

**Comment by xiaole29999** [comment]
> 已经解决

我撤回这句话，有些人还是不行...

**Comment by xiaole29999** [comment]
![image](https://user-images.githubusercontent.com/111669037/186354772-4789e345-45f5-4dfa-86f5-67e6187ea5fa.png)

**Comment by xiaole29999** [comment]
我怀疑是他的名字有特殊字符的原因：
![image](https://user-images.githubusercontent.com/111669037/186354879-c9ab17d3-ba06-4a62-b5c9-6a6ecd8f0ab6.png)

**Comment by XiaMoHuaHuo-CN** [comment]
> ![image](https://user-images.githubusercontent.com/111669037/186354772-4789e345-45f5-4dfa-86f5-67e6187ea5fa.png)

能把我拉进你服务器吗 我试试
我QQ 2549619802

**Comment by xiaole29999** [comment]
我先重启下服务器吧，可能是我热重载的原因

**Comment by xiaole29999** [comment]
> 2549619802

已经加好友了麻烦，同意一下

**Comment by XiaMoHuaHuo-CN** [comment]
经测试未能排除问题，暂时确认为上游问题
