### ISSUE TITLE
添加转发对颜色代码和papi的支持

### ISSUE THREAD

**Issue by xiaole29999** [XiaMoHuaHuo-CN/CatSero#21]
### 功能描述

建议添加转发对颜色代码和papi的支持

### 使用方法

如下：
  format:
    to-mc: "**_&a_**[QQ][%groupname%]%sendername%:%message%"
    to-qq: "[MC]**_%player_world%_**%player%:%message%"

**Comment by XiaMoHuaHuo-CN** [comment]
请查看最新构建
https://github.com/XiaMoHuaHuo-CN/CatSero/actions/runs/2916823862
PAPI其实我已经写了

**Comment by XiaMoHuaHuo-CN** [comment]
https://github.com/XiaMoHuaHuo-CN/CatSero/actions/runs/2916837258

**Comment by xiaole29999** [comment]
构建没成功啊...


> 请查看最新构建 https://github.com/XiaMoHuaHuo-CN/CatSero/actions/runs/2916823862 PAPI其实我已经写了

**Comment by xiaole29999** [comment]
> https://github.com/XiaMoHuaHuo-CN/CatSero/actions/runs/2916837258

OKOK
