### ISSUE TITLE
Trchat聊天转发无效

### ISSUE THREAD

**Issue by 35gif730** [XiaMoHuaHuo-CN/CatSero#31]
### 问题描述

在QQ群内发送消息可转发至服务器内
但使用Trchat发送消息无法转发至服务器内

### 复现方法

1. 在服务器内使用Trchat发送消息

### 服务端版本

Paper-1.19.1

### CatSero 版本

Catsero V1.2-Pre3

### 服务端日志

```text
日志过多 上传至附件
```

### 额外说明

系统环境 Win Server 2012 R2 Build 9600
CPU 英特尔 Xeon E5-2650 V2 @ 2.60Ghz
内存 8G
Java版本 Java17
重新安装Catsero/Trchat
重载Catsero/Trchat配置文件均无效
[latest.log](https://github.com/XiaMoHuaHuo-CN/CatSero/files/9545079/latest.log)

**Comment by XiaMoHuaHuo-CN** [comment]
请问你调了聊天频道吗

**Comment by XiaMoHuaHuo-CN** [comment]
我这边测试是没有问题的

**Comment by XiaMoHuaHuo-CN** [comment]
看你这边使用的是v1 v2的转发是没问题的 如果要建议用v2而不是v1

**Comment by 35gif730** [comment]
> 看你这边使用的是v1 v2的转发是没问题的 如果要建议用v2而不是v1

使用最新的v2 beta仍然无效 各类信息已全部填写

**Comment by XiaMoHuaHuo-CN** [comment]
能把配置文件以及/catsero version发出来吗

**Comment by 35gif730** [comment]
> 能把配置文件以及/catsero version发出来吗

好的

**Comment by 35gif730** [comment]
[CatSero V1.2 Pre3[后期改名].zip](https://github.com/XiaMoHuaHuo-CN/CatSero/files/9546144/CatSero.V1.2.Pre3.zip)
![Y%JAN}4Q@0A}U3Z(KKKWXCY](https://user-images.githubusercontent.com/80586911/189606706-6403944e-4605-4b2e-89f7-a51188a6d7fa.png)

**Comment by XiaMoHuaHuo-CN** [comment]
不不不 我指v2的

**Comment by 35gif730** [comment]
> 不不不 我指v2的

V2的verison指令貌似没有配置好 执行显示无效的参数

**Comment by XiaMoHuaHuo-CN** [comment]
你打错了 是`version`而不是`verison`

**Comment by 35gif730** [comment]
> 你打错了 是`version`而不是`verison`

抱歉看错了

**Comment by 35gif730** [comment]
> 你打错了 是`version`而不是`verison`

但是打成正确的显示不正确的参数格式
![S0JQH~O32EFW2~@UL@(NGN1](https://user-images.githubusercontent.com/80586911/189607958-0ef3773d-beb6-4ea2-802e-8dcc30a159b1.png)

**Comment by XiaMoHuaHuo-CN** [comment]
等我一下

**Comment by XiaMoHuaHuo-CN** [comment]
尝试Actions的最新构建

**Comment by 35gif730** [comment]
> 尝试Actions的最新构建

还是和前面一样
[CatSero V2.0 Beta[后期改名].zip](https://github.com/XiaMoHuaHuo-CN/CatSero/files/9546317/CatSero.V2.0.Beta.zip)
游戏内消息不可发送到群
群内消息可发送到游戏

**Comment by XiaMoHuaHuo-CN** [comment]
你channel里面好像没有写你要转发的频道?
![Uploading Screenshot_20220912_164512_bin.mt.plus.jpg…]()

**Comment by XiaMoHuaHuo-CN** [comment]
![Screenshot_20220912_164512_bin mt plus](https://user-images.githubusercontent.com/79651409/189611254-9a993915-5371-4d78-b6f9-b0a8f5e662be.jpg)

**Comment by 35gif730** [comment]
> 你channel里面好像没有写你要转发的频道?

Trchat里default默认频道是Normal 我也是在Normal里发言的

**Comment by 35gif730** [comment]
> 你channel里面好像没有写你要转发的频道?

但是我改成Global/Default/Staff也是一样无效

**Comment by XiaMoHuaHuo-CN** [comment]
> > 你channel里面好像没有写你要转发的频道?
> 
> 但是我改成Global/Default/Staff也是一样无效

你不应该把Normal写进去吗

**Comment by 35gif730** [comment]
> > > 你channel里面好像没有写你要转发的频道?
> > 
> > 
> > 但是我改成Global/Default/Staff也是一样无效
> 
> 你不应该把Normal写进去吗

也是无效😂

**Comment by 35gif730** [comment]
> > > 你channel里面好像没有写你要转发的频道?
> > 
> > 
> > 但是我改成Global/Default/Staff也是一样无效
> 
> 你不应该把Normal写进去吗

也是无效

**Comment by XiaMoHuaHuo-CN** [comment]
我去 我裂开 测试的时候还能的

**Comment by 35gif730** [comment]
> 我去 我裂开 测试的时候还能的

好像可以了 我换了个账号 但是原来的那个账号没被封 也没干什么就不能发

**Comment by XiaMoHuaHuo-CN** [comment]
> > 我去 我裂开 测试的时候还能的
> 
> 好像可以了 我换了个账号 但是原来的那个账号没被封 也没干什么就不能发

是因为tx新增人机监测封禁吧

**Comment by XiaMoHuaHuo-CN** [comment]
不过你帮我找到了另一个bug——version指令无效😂

**Comment by 35gif730** [comment]
> 不过你帮我找到了另一个bug——version指令无效😂

也还有一个Bug

**Comment by 35gif730** [comment]
> 不过你帮我找到了另一个bug——version指令无效😂

不同群消息有概率会串

**Comment by XiaMoHuaHuo-CN** [comment]
> > 不过你帮我找到了另一个bug——version指令无效😂
> 
> 不同群消息有概率会串

这是上游问题了

**Comment by 35gif730** [comment]
> > > 不过你帮我找到了另一个bug——version指令无效😂
> > 
> > 
> > 不同群消息有概率会串
> 
> 这是上游问题了

那谢谢了哈 问题我就关了哈
