### ISSUE TITLE
bc群组服聊天互通转发

### ISSUE THREAD

**Issue by Potyz-0** [XiaMoHuaHuo-CN/CatSero#36]
### 功能描述

在多个子服组成的群组服中分别发送消息，机器人可一一进行转发

### 使用方法

1. 把插件装载到bc服，子服无需装载
2. 插件开始获取配置文件内的bc子服配置，如未开启此功能，则默认关闭
3. 插件加载成功开始监听各个子服的聊天消息，如有新发出的聊天消息，立刻转发至群聊

**Comment by XiaMoHuaHuo-CN** [comment]
我并不熟悉bc的API，有空再看看吧
