### ISSUE TITLE
建议精简QQ群命令

### ISSUE THREAD

**Issue by Moraxyc** [XiaMoHuaHuo-CN/CatSero#59]
### 功能描述

原因: 
作为了解插件的腐竹，catsero这个名字肯定能够记住的，但群员不大可能把这个记住且使用。

建议: 
1. 将命令精简
2. 设定权限节点，可设定开放给群员使用

### 使用方法

e.g. 
1. 指令精简
        * `!catsero list`修改为`!clist`
        * `!catsero tps around`修改为`!ctps`
2. 权限节点
        * `catsero.command.qq.list`
        * `catsero.command.qq.tps`

**Comment by XiaMoHuaHuo-CN** [comment]
收到

**Comment by XiaMoHuaHuo-CN** [comment]
关于权限节点这个，有点难绷，没有统一的API

**Comment by XiaMoHuaHuo-CN** [comment]
关于权限节点这个，有点难绷，没有统一的API

**Comment by Moraxyc** [comment]
我有两种解决的想法：

## 第一种：通过mc权限判断

我看到你有计划集成Whitelist4QQ的全部功能，而Whitelist4QQ就简化了QQ与MC账户的绑定。权限节点这个功能在QQ上很难实现不如直接同步mc中的权限设置。

例如：
mc中赋予了Default组`catsero.command.qq.list`权限，那么当QQ群内有人使用`!clist`时，就会获取miraimc中的绑定数据并判断该QQ号对应的mc账户是否具有使用权限再进行下一步。

至于那些没绑定的用户：
没绑定账户说明根本没进白名单
~~连服务器都进不去还要命令执行权干嘛~~

## 第二种：配置文件中配置

在配置文件中给命令添加一行`是否运行普通成员使用`这个配置项

我的想法是这样的，如果实现过于麻烦就算了

**Comment by XiaMoHuaHuo-CN** [comment]
## 第一种

并不是所有服务器都存在白名单

## 第二种

(又逼我改配置)
或者我自己出一套权限API(累死

## 其他想法

可以通过管理员，群员，群主这种权限判断

我不是很赞同第一种，第二种可以看看

**Comment by Moraxyc** [comment]
确实，我的服全都开了白名单，有些忽略了那些没开白名单的。

第二种的话权限就可以说仅存在管理员/群员两种权限层级（群主的不确定性有点大，比如我的QQ群主就是bot。。。），不过对于简单指令来说应该足够了

**Comment by XiaMoHuaHuo-CN** [comment]
我可以定义一个列表，来设置权限，就有点相当于自己的权限系统

**Comment by XiaMoHuaHuo-CN** [comment]
关于命令那个，命令是统一的解析器而不是简单的equals，所以这个需要我继续研究

**Comment by Moraxyc** [comment]
权限那个我觉得这样就够了，毕竟再大的服务器也不可能有几十位指定权限的用户吧（

命令那个我就提不了太多建议了，没学过java（不然就会直接提PR了😩）

catsero在miraimc插件中属于强大的一类了，希望越来越好！

**Comment by XiaMoHuaHuo-CN** [comment]
决定做一下

**Comment by XiaMoHuaHuo-CN** [comment]
已完成
