### ISSUE TITLE
[功能请求]白名单申请时绑定QQ以防重复申请

### ISSUE THREAD

**Issue by Moraxyc** [XiaMoHuaHuo-CN/CatSero#68]
### 功能描述

如题

### 使用方法

1. 数据库多加一个表格，储存QQ号
2. 群内申请白名单后，QQ号与用户名对应写入数据库
3. 申请白名单时，从数据库读取QQ判断是否已绑定用户名，已绑定用户名则更新原有记录，未绑定用户名则新增记录
4. 管理员命令可强制新增白名单用户名而无需绑定QQ

**Comment by XiaMoHuaHuo-CN** [comment]
完成
1，2，3需要管理员手动修改数据库，4不允许无QQ绑定的白名单
