### ISSUE TITLE
Could not pass event TrChatEvent to CatSero v2.2

### ISSUE THREAD

**Issue by 1240798440** [XiaMoHuaHuo-CN/CatSero#72]
### 问题描述

开服后我一进去就刷了这个报错

TrChat-2.0.0-RC-6 
Mirai-MC-1.7
我已经用了miraimc命令绑定了游戏账户与qq
https://pastebin.com/MtyW6rr4

### 复现方法

服务器启动后

### 服务端版本

Paper-376-1.19.3

### CatSero 版本

2.2

### 服务端日志

```text
https://pastebin.com/adrxyQ6V
```

### 额外说明

Java18
插件列表:
![image](https://user-images.githubusercontent.com/28185841/212446280-736dd914-cdc7-4085-955c-86a49c2e4998.png)
![image](https://user-images.githubusercontent.com/28185841/212446287-f9c6663d-bbcc-4716-aa1b-9d1832e4b52f.png)

**Comment by XiaMoHuaHuo-CN** [comment]
你可能有插件和本插件冲突?
这里直接初始化失败了

**Comment by XiaMoHuaHuo-CN** [comment]
另外请提供整个`latest.log`

**Comment by 1240798440** [comment]
那个pastebin

> 另外请提供整个`latest.log`

俩个pastebin链接，下面那个是日志

**Comment by XiaMoHuaHuo-CN** [comment]
请删除整个locale文件夹试试

**Comment by 1240798440** [comment]
> 请删除整个locale文件夹试试

解决了，谢谢。
