### ISSUE TITLE
聊天转发过滤该怎么配置呢

### ISSUE THREAD

**Issue by 1240798440** [XiaMoHuaHuo-CN/CatSero#73]
### 问题描述

我是这样配置的:
https://pastebin.com/mZP977Vq
然后进游戏说句话就刷了日志报错:
https://pastebin.com/teGDJEUr

### 复现方法

发送一条消息

### 服务端版本

paper-1.19.3

### CatSero 版本

2.2

### 服务端日志

```text
https://pastebin.com/y7KiMykG
```

**Comment by XiaMoHuaHuo-CN** [comment]
请移除远程源，远程词库下载失败导致报错
