### ISSUE TITLE
catsero reload 不能重载bot和group信息

### ISSUE THREAD

**Issue by wanyanjiabin** [XiaMoHuaHuo-CN/CatSero#77]
### 问题描述

刚才那个问题,我修改好配置后一直没有重启服务器,一直使用命令catsero reload,以为会重新加载bot.yml和group.yml的数据,所以一直报错.
重启启动服务器之后可以正常识别了.
所以可以验证 catsero reload 无法重新加载bot.yml和group.yml的数据.
期望可以通过catsero reload 命令一并重载bot.yml和group.yml的数据.
如果本就没有这个设计,请忽略本次提交
再次感谢提供这么好的插件,谢谢

### 复现方法

1. 

### 服务端版本

paper-1.19.2

### CatSero 版本

2.2

### 服务端日志

```text
无
```

**Comment by XiaMoHuaHuo-CN** [comment]
你说的这个功能我无法实现，如果需要请使用PlugManX热重载

**Comment by wanyanjiabin** [comment]
好的,感谢回复
