### ISSUE TITLE
Add support for reloading more configuration files with commands

### ISSUE THREAD

**Issue by Zhou-Shilin** [XiaMoHuaHuo-CN/CatSero#82]
### 功能描述

目前/catsero reload指令仅能重载config.yml文件，希望在新版本中能重载其他配置文件awa

The command /catsero reload only can reload config.yml instead of all the configuration files, plz add support for it in the next version! XD

### 使用方法

/catsero reload [file]
_file非必填项，可选参数见下_
_Non-mandatory, parameters:_

_all(default), config, uses-config, mirai-config, extra-config_

### 额外说明

希望插件越做越好！之后还会提几个建议，望采纳～

**Comment by XiaMoHuaHuo-CN** [comment]
请见 #77 
![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)

主要是我懒得研究了 而且马上开学了 暂时不想更新 (

**Comment by Zhou-Shilin** [comment]
> 请见 #77 ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif) [ ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif) ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif) [ ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> 
> 主要是我懒得研究了 而且马上开学了 暂时不想更新 (

可恶qwq

**Comment by XiaMoHuaHuo-CN** [comment]
> > 请见 #77 ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >       
> >         [
> >           
> >             ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >           
> >         ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >         
> >        [ ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif) ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >       
> >         [
> >           
> >             ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >           
> >         ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > 主要是我懒得研究了 而且马上开学了 暂时不想更新 (
> 
> 可恶qwq

可以考虑用PluginManX重载整个插件，不会出问题的XD

**Comment by Zhou-Shilin** [comment]
> > > 请见 #77 ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >       
> > >         [
> > >           
> > >             ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >           
> > >         ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >         ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >       
> > >     ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >     
> > >    [ ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif) ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >   
> > >     [
> > >       
> > >         ![-7051901a6e3c7863](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >       
> > >     ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > >     
> > >    [ ](https://user-images.githubusercontent.com/79651409/214260013-4c33d310-fe91-4dd7-a562-a8568a4192d4.gif)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 主要是我懒得研究了 而且马上开学了 暂时不想更新 (
> > 
> > 
> > 可恶qwq
> 
> 可以考虑用PluginManX重载整个插件，不会出问题的XD

好的谢谢
