### ISSUE TITLE
关于优化互通服白名单申请使用体验的建议

### ISSUE THREAD

**Issue by Natsusomekeishi** [XiaMoHuaHuo-CN/CatSero#90]
### 功能描述

部分玩家没遵循Java版ID，可以采取新加一个判定，例如ID“ABC ABC”中间有空格，如果玩家这样绑定，就提示，无法绑定，请绑定符合Java版的白名单名称，这样的功能。

### 使用方法

1. 玩家发送“申请白名单 XXX XXX”
2. 机器人提示“无法绑定含有空格的用户名，请修改或更换用户名后重新绑定”
3. 控制台警告“该服未添加floodgate插件，无法绑定含有空格的用户名”

**Comment by XiaMoHuaHuo-CN** [comment]
#83

**Comment by Natsusomekeishi** [comment]
有些服务器（例如我）可能并不是很想添加floodgate插件，采取authme或者catseedlogin内置登录，使得同一玩家ID可以同时使用一个Java的背包数据。

**Comment by XiaMoHuaHuo-CN** [comment]
> 有些服务器（例如我），开的是审核制私服，可能并不是很想添加floodgate插件，采取authme或者catseedlogin内置登录，使得同一玩家ID可以同时使用一个Java的背包数据，方便玩家同时使用一个ID来多端游玩，希望可以添加此功能。

Geyser应与Floodgate一起使用，如需兼容也必须调用Floodgate API，而你说的同一ID，如UUID不同会导致混乱，Bukkit识别一个玩家不是靠名字而是靠UUID，这么做就是打乱了Bukkit的运行机制，应该使用Floodgate的绑定功能而不是简单的同名

**Comment by Natsusomekeishi** [comment]
我这边无论是粘液科技玩法的互通服还是生电纯生存互通服，都没有采用floodgate插件，而是启用offine登录，玩家的数据是通过用户名同步的，我不清楚是为什么，如果采用floodgate插件的登录，会导致基岩版玩家名前面加“.”而强制变成另外一个账户。

**Comment by XiaMoHuaHuo-CN** [comment]
> 我这边无论是粘液科技玩法的互通服还是生电纯生存互通服，都没有采用floodgate插件，而是启用offine登录，玩家的数据是通过用户名同步的，我不清楚是为什么，如果采用floodgate插件的登录，会导致基岩版玩家名前面加“.”而强制变成另外一个账户。

Floodgate配置文件中有名称前缀功能，可以配置

**Comment by Natsusomekeishi** [comment]
我知道的，如果设置成空白，也会强制使用“.”，即无法设置成空白前缀

**Comment by XiaMoHuaHuo-CN** [comment]
Floodgate API

https://github.com/GeyserMC/Floodgate/blob/master/api/src/main/java/org/geysermc/floodgate/api/FloodgateApi.java
