### ISSUE TITLE
关于机器人修改群名片/头衔/群名片/群资料的功能建议

### ISSUE THREAD

**Issue by Natsusomekeishi** [XiaMoHuaHuo-CN/CatSero#91]
### 功能描述

不知道QQ机器人目前是否可以修改群名片/头衔/群名片/群资料。
不过因为我之前在其他机器人上面看到过，群名片可以改。

希望可以新增一个变量，用户可以把这个变量添加到上述位置，启动服务器之后，机器人匹配该变量，实时于群名片/头衔/群名片/群资料（可以调整延迟）更改为对应数据，比如在线玩家数量之类的，或者TPS之类的。

### 使用方法

1. 例如，我关闭服务端，原本群名“XX服务器”我更改为“XX服务器 - !!C”，这个`!!C`就是变量。
2. 启动游戏之后，新的配置文件中记录这个变量位置，并更改为“变量配置中”。
3. 我可以更改机器人修改的内容，例如通过现有变量改为“在线玩家数量”。
4. 重载之后，此位置改为“XX服务器 - 在线3人”，其中在线%人可以修改，同时关闭服务端之后，该位置会恢复成“!!C”。
5. 如果服务端重启或者关闭，也可以另行设置修改为“服务器已关闭”、“服务器重启中”。
6. 变量一经替换，需要玩家重新添加变量才能使用该功能。（此内容可忽略）
7. PS：同理，机器人群名片可以改为实时TPS显示之类的内容。

### 额外说明

这将是一个开创性的更新，希望CatSero作为目前兼容功能最多的插件，可以再添加新内容！阿里嘎多~

**Comment by XiaMoHuaHuo-CN** [comment]
#83

**Comment by XiaMoHuaHuo-CN** [comment]
根据 Javadoc ，找到了群名称/Bot名称/头衔的方法：

- https://jd.miraimc.dreamvoid.me/me/dreamvoid/miraimc/api/bot/group/MiraiNormalMember#setNameCard(java.lang.String)
- https://jd.miraimc.dreamvoid.me/me/dreamvoid/miraimc/api/bot/group/MiraiNormalMember#setSpecialTitle(java.lang.String)
- https://jd.miraimc.dreamvoid.me/me/dreamvoid/miraimc/api/bot/MiraiGroup#setName(java.lang.String)

**Comment by Natsusomekeishi** [comment]
变量可以多元化，除在线人数，开服状态等，还可以使用网上常见的一言api，通过设置更换/刷新时间，实现每天更换。
ps：刚刚突然发现朋友的服务器标题上面以“XX服 - XXXX”的形式显示格言，有了这个点子hhh。

**Comment by XiaMoHuaHuo-CN** [comment]
外置api没统一格式感觉不是很好对接（
