### ISSUE TITLE
关于群公告发布时游戏内刷屏的优化需求

### ISSUE THREAD

**Issue by Natsusomekeishi** [XiaMoHuaHuo-CN/CatSero#93]
### 功能描述

群内发布群公告，由于Mirai机器人的问题，会导致大量代码被同步到游戏中，造成刷屏的情况，如：
`{"app":"com.tencent.mannounce","config":{"ctime":XXXXXXXX,"forward":0,"token":"XXXXXXXX"},"desc":"群公告","extra":{"app_type":1,"appid":XXXXXXXX,"uin":XXXXXXXX},"meta":{"mannounce":{"cr":0,"encode":1,"fid":"9d4e58060
0000000876bd4630efa0700","gc":"XXXXXXXX","sign":"fcc188777727a1392ac2285f78d4f429","text":"5py65Zmo5Lq65L+u5aW95LqGcXdx","title":"576k5YWs5
ZGK","tw":0,"uin":"1291596219"}},"prompt":"[群公告]XXXXXXXX","ver":"1.0.0.43","view":"main"}`

### 使用方法

1. 可以设置是否接受群公告内容。
2. 无论是否接受，上述群公告都会被转发为“[XXX发布群公告]内容”

**Comment by Zhou-Shilin** [comment]
在群成员发布从其他App分享的链接、小程序、群帖子也会出现同样的情况 :(

**Comment by XiaMoHuaHuo-CN** [comment]
这是miraimc的锅(

**Comment by XiaMoHuaHuo-CN** [comment]
说明：

1. 简单的判定可以去除这个消息
2. 腾讯的公告内容只是缩略，目前无法获取完整公告
