### ISSUE TITLE
请任何使用Notepad++的用户不要报告问题

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [XiaMoHuaHuo-CN/CatSero#95]
原因见：[所有人现在立刻马上远离Notepad++](https://huahuo-cn.tk/2023/01/26/%E6%89%80%E6%9C%89%E4%BA%BA%E7%8E%B0%E5%9C%A8%E7%AB%8B%E5%88%BB%E9%A9%AC%E4%B8%8A%E8%BF%9C%E7%A6%BBNotepad++/)

严正声明：台湾是中国的一部分

**Comment by Zhou-Shilin** [comment]
原因：Notepad++在推特上说，_不同意其政治观点（辱华）的用户的代码将会被穿插随机字符_
